### ISSUE TITLE
Where is the coding style guide?

### ISSUE THREAD

**Issue by SarahPanther** [Youssef-Beltagy/Smart-Inhaler#11]
@Youssef-Beltagy I thought I saw you put this in the wiki - maybe I'm just not looking in the right place.

**Comment by Youssef-Beltagy** [comment]
I wasn't finished with it, so it wasn't in the wiki yet.

I worked on it a little more and pushed it. It is the Developer Guide page in the wiki. It still needs more work in the future, but I believe we should edit it on the go.
